chat/urls.py
from django.urls import path, re_path
from .views import index, room

app_name = 'chat'

urlpatterns = [
    # path('', index, name="index"),
    re_path(r'^(?P<room_name>[^/]+)/$', room, name='room')
]

chatdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import logout_then_login

from person.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/',include('chat.urls', namespace='chat')),
    path('person/',include('person.urls', namespace='person')),
    path('', LoginView.as_view(), name='login'),
    path('logout/', logout_then_login, name='logout'),
    path('accounts/login/', LoginView.as_view(), name='index'),
]

person/urls.py
from django.urls import path, re_path
from .views import CreateUser

app_name = 'person'

urlpatterns = [
    # path('', index, name="index"),
    re_path(r'^create/$', CreateUser.as_view(), name='create'),
]

chat/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

class Message(models.Model):
    author = models.ForeignKey(User, related_name='author_messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp =models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author.username
    def last_10_message():
        return Message.objects.order_by('-timestamp').all()[:10]

person/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class LoggedInUser(models.Model):
    # User-Session one to one
    user = models.OneToOneField(User, related_name='logged_in_user', on_delete=models.CASCADE)
    session_key = models.CharField(max_length=32, blank=True, null=True)

    def __str__(self):
        return self.user.username

person/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CreateForm(UserCreationForm):

    class Meta:
        model= User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]
        labels = {
            'username': 'User',
            'first_name': 'Name',
            'last_name': 'Last name',
            'email': 'Email',
        }

    # validations for registration
    
    def clean_email(self):
        check_email = self.cleaned_data['email']
        storage_email = User.objects.filter(email=check_email)

        if storage_email.exists():
            raise forms.ValidationError('Email already exists')

        if check_email.isspace():
            raise forms.ValidationError('Email cannot contain spaces')

        if len(check_email) == 0:
            raise forms.ValidationError('Email required')

        return check_email

    def clean_username(self):
        check_username = self.cleaned_data['username']

        if len(check_username) < 3:
            raise forms.ValidationError('User must has 4 characters or more')

        return check_username

chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.safestring import mark_safe
from django.contrib.auth import get_user_model
# from django.http import HttpResponseRedirect
# from django.urls import reverse_lazy
from .models import Message
from person.models import LoggedInUser
import json

User = get_user_model()

def index(request):
    return render(request, 'chat/index.html', {})

@login_required
def room(request, room_name):
    person = User.objects.filter(username=request.user.username)
    
    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(room_name)),
        'username': mark_safe(json.dumps(request.user.username)),
        'person': person,
    })

person/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.generic import CreateView, FormView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth import login
from django.urls import reverse_lazy
from .forms import CreateForm

class CreateUser(SuccessMessageMixin, CreateView):
    model = User
    template_name = 'person/create.html'
    form_class = CreateForm
    success_url = reverse_lazy('login')
    success_message = 'User created'

    def form_valid(self, form):
        data = form.instance
        data.user_id = self.request.user.id
        self.object = form.save()
        return super(CreateUser, self).form_valid(form)


    def dispatch(self, *args, **kwargs):
        return super(CreateUser, self).dispatch(*args, **kwargs)


class LoginView(SuccessMessageMixin, FormView):
    form_class = AuthenticationForm
    template_name = 'login.html'
    success_url = reverse_lazy('chat:room',args=['public'])

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(LoginView, self).dispatch(request, *args, **kwargs)

    

chat/templates/chat/chat.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


<html>
<head>

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet"

</head>
<body>
<div class="container">
<h3 class=" text-center">Messaging</h3>
<div class="messaging">
      <div class="inbox_msg">
        <div class="inbox_people">
          <div class="headind_srch">
            <div class="recent_heading">
              <h4>Recent</h4>
            </div>
            <div class="srch_bar">
              <div class="stylish-input-group">
                <input type="text" class="search-bar"  placeholder="Search" >
                <span class="input-group-addon">
                <button type="button"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                </span> </div>
            </div>
          </div>
          <div class="inbox_chat">
            <div class="chat_list active_chat">
              <div class="chat_people">
                <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                <div class="chat_ib">
                  <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                  <p>Test, which is a new approach to have all solutions 
                    astrology under one roof.</p>
                </div>
              </div>
            </div>
            <div class="chat_list">
              <div class="chat_people">
                <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                <div class="chat_ib">
                  <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                  <p>Test, which is a new approach to have all solutions 
                    astrology under one roof.</p>
                </div>
              </div>
            </div>
            <div class="chat_list">
              <div class="chat_people">
                <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                <div class="chat_ib">
                  <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                  <p>Test, which is a new approach to have all solutions 
                    astrology under one roof.</p>
                </div>
              </div>
            </div>
            <div class="chat_list">
              <div class="chat_people">
                <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                <div class="chat_ib">
                  <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                  <p>Test, which is a new approach to have all solutions 
                    astrology under one roof.</p>
                </div>
              </div>
            </div>
            <div class="chat_list">
              <div class="chat_people">
                <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                <div class="chat_ib">
                  <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                  <p>Test, which is a new approach to have all solutions 
                    astrology under one roof.</p>
                </div>
              </div>
            </div>
            <div class="chat_list">
              <div class="chat_people">
                <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                <div class="chat_ib">
                  <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                  <p>Test, which is a new approach to have all solutions 
                    astrology under one roof.</p>
                </div>
              </div>
            </div>
            <div class="chat_list">
              <div class="chat_people">
                <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                <div class="chat_ib">
                  <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                  <p>Test, which is a new approach to have all solutions 
                    astrology under one roof.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="mesgs">
          <div class="msg_history">
            <div class="incoming_msg">
              <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
              <div class="received_msg">
                <div class="received_withd_msg">
                  <p>Test which is a new approach to have all
                    solutions</p>
                  <span class="time_date"> 11:01 AM    |    June 9</span></div>
              </div>
            </div>
            <div class="outgoing_msg">
              <div class="sent_msg">
                <p>Test which is a new approach to have all
                  solutions</p>
                <span class="time_date"> 11:01 AM    |    June 9</span> </div>
            </div>
            <div class="incoming_msg">
              <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
              <div class="received_msg">
                <div class="received_withd_msg">
                  <p>Test, which is a new approach to have</p>
                  <span class="time_date"> 11:01 AM    |    Yesterday</span></div>
              </div>
            </div>
            <div class="outgoing_msg">
              <div class="sent_msg">
                <p>Apollo University, Delhi, India Test</p>
                <span class="time_date"> 11:01 AM    |    Today</span> </div>
            </div>
            <div class="incoming_msg">
              <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
              <div class="received_msg">
                <div class="received_withd_msg">
                  <p>We work directly with our designers and suppliers,
                    and sell direct to you, which means quality, exclusive
                    products, at a price anyone can afford.</p>
                  <span class="time_date"> 11:01 AM    |    Today</span></div>
              </div>
            </div>
          </div>
          <div class="type_msg">
            <div class="input_msg_write">
              <input type="text" class="write_msg" placeholder="Type a message" />
              <button class="msg_send_btn" type="button"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>
            </div>
          </div>
        </div>
      </div>
      
      
      <p class="text-center top_spac"> Design by <a target="_blank" href="#">Sunil Rajput</a></p>
      
    </div></div>
    </body>
    </html>

chat/templates/chat/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
{% extends "base.html" %} {% load static %}
{% block titulo %} Chat Room {% endblock titulo %}

{% block extrahead %}
<link href="{% static 'style.css' %}" type="text/css" rel="stylesheet">
{% endblock%}

{% block content %}
<!-- <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/> -->

<h3 class=" text-center">Public chat</h3>
<div class="messaging">
    <div class="inbox_msg">
        <div class="inbox_people col-xs-12">
            <div class="headind_srch">
                <div class="recent_heading">
                    <h4>{{person.0.username}}</h4>
                </div>
                <div class="srch_bar">
                    <div class="stylish-input-group">
                        <a href="{% url "logout" %}" class="float-right btn btn-outline-primary mt-1">Log out</a>
                    </div>
                </div>
            </div>
            <div class="inbox_chat">

                <div class="chat_list active_chat">
                    <div class="recent_heading">
                        <h4>User info</h4>
                    </div>
                    <br><br>
                    <div class="chat_people">
                        <div class="chat_img">
                            <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil">
                        </div>
                        <div class="chat_ib">
                            <h5><b>First name </b>{{person.0.first_name}}</h5>
                            <h5><b>Last name </b> {{person.0.last_name}}</h5>
                            <p><b>Email </b> {{person.0.email}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mesgs col-xs-12">
            <div id="chat-log" class="msg_history">

            </div>
            <div class="type_msg">
                <div class="input_msg_write">
                    <input id="chat-message-input" type="text" class="write_msg" placeholder="Type a message" />
                    <button id="chat-message-submit" class="msg_send_btn" type="button"><i class="fa fa-paper-plane-o"
                            aria-hidden="true"></i></button>
                </div>
            </div>
        </div>
    </div>

</div>


<script src="{% static 'reconnecting-websocket.js' %}"></script>
<script>

</script>
<script>
    var roomName = {{ room_name_json }};
    var username = {{ username }};

    var chatSocket = new ReconnectingWebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    // load last 10 messages
    chatSocket.onopen = function (e) {
        fetchMessages();
    }

    // verify command
    chatSocket.onmessage = function (e) {
        var data = JSON.parse(e.data);
        if (data['command'] === 'messages') {
            for (let i = 0; i < data['messages'].length; i++) {
                createMessage(data['messages'][i]);
            }
        } else if (data['command'] === 'new_message') {
            if (data['message']['content'] != "") {
                createMessage(data['message']);
            }

        }
    };

    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    // send message with key enter (calls event click)
    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    // send message with click
    document.querySelector('#chat-message-submit').onclick = function (e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'command': 'new_message',
            'message': message,
            'from': username
        }));

        messageInputDom.value = '';
    };
    // show last 10
    function fetchMessages() {
        chatSocket.send(JSON.stringify({ 'command': 'fetch_messages' }));
    }

    // show message in html
    function createMessage(data) {
        var author = data['author'];
        var divTag = document.createElement('div');
        var divTagTyp = document.createElement('div');


        var time = document.createElement('span');
        time.textContent = data.timestamp.toLocaleString();
        time.className = 'time_date';
        var pTag = document.createElement('p');
        var bTag = document.createElement('b');
        bTag.textContent = author + ' ';
        pTag.innerHTML = "<p><b>" + author + "</b>: " + data.content + "<p>";

        if (author === username) {
            divTag.className = 'incoming_msg';
            divTagTyp.className = 'sent_msg';
            divTagTyp.appendChild(pTag);
            divTagTyp.appendChild(time);
        } else {
            divTag.className = 'outgoing_msg';
            var divTagRecMes = document.createElement('div');
            divTagRecMes.className = 'received_withd_msg';
            divTagTyp.className = 'received_msg';

            divTagRecMes.appendChild(pTag);
            divTagRecMes.appendChild(time);
            divTagTyp.appendChild(divTagRecMes)
        }
        // show new message
        divTag.appendChild(divTagTyp);
        document.querySelector('#chat-log').appendChild(divTag);
        // automatic scroll
        var area = document.getElementById('chat-log');
        area.scrollTop = area.scrollHeight;
    }
</script>
{% endblock %}

person/templates/person/create.html
{% extends "base.html" %} {% load static %}
{% block titulo %} Create {% endblock titulo %}

{% block extrahead %}
<link href="{% static 'style.css' %}" type="text/css" rel="stylesheet">
{% endblock%}

{% block content %}


    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <header class="card-header">
                    <a href="{% url "login" %}" class="float-right btn btn-outline-primary mt-1">Log in</a>
                    <h4 class="card-title mt-2">Sign up</h4>
                </header>
                <article class="card-body">
                    {% if messages %}
                        {% for message in messages %}
                        <p class="text-success">{{message}}</p>
                        {% endfor %}
                    {% endif %}
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <p class="text-danger">{{ error|escape }}</p>
                            {% endfor %} 
                        {% endfor %}
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>User</label>
                            <input class="form-control" type="text" name="username" required>
                        </div> <!-- form-group end.// -->
                        <div class="form-row">
                            <div class="col form-group">
                                <label>First name </label>
                                <input type="text" class="form-control" placeholder="" name="first_name" required>
                            </div> <!-- form-group end.// -->
                            <div class="col form-group">
                                <label>Last name</label>
                                <input type="text" class="form-control" placeholder=" " name="last_name" required>
                            </div> <!-- form-group end.// -->
                        </div> <!-- form-row end.// -->
                        <div class="form-group">
                            <label>Email address</label>
                            <input type="email" class="form-control" placeholder="" name="email" required>
                            <small class="form-text text-muted">We'll never share your email with anyone else.</small>
                        </div> <!-- form-group end.// -->
                        <div class="form-group">
                            <label>Create password</label>
                            <input class="form-control" type="password" name="password1" required>
                        </div> <!-- form-group end.// -->
                        <div class="form-group">
                                <label>Repeat password</label>
                                <input class="form-control" type="password" name="password2" required>
                            </div> <!-- form-group end.// -->
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Register </button>
                        </div> <!-- form-group// -->
                        <small class="text-muted">By clicking the 'Sign Up' button, you confirm that you accept our <br>
                            Terms of use and Privacy Policy.</small>
                    </form>
                </article> <!-- card-body end .// -->
                <div class="border-top card-body text-center">Have an account? <a href="{% url "login" %}">Log In</a></div>
            </div> <!-- card.// -->
        </div> <!-- col.//-->

    </div> <!-- row.//-->


{% endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css"
        rel="stylesheet">
    {% block extrahead %}
    {% endblock%}
</head>
<body>
    <div class="container">
        <div class="row"><br></div>
        {% block content %}			
	    {% endblock %}
    </div>
    
</body>
<script>
    {% if message %}
        var msj= {{message}};
        console.log(msj);
    {% endif %}
</script>
</html>

templates/login.html
{% extends "base.html" %} {% load static %}
{% block titulo %} Login {% endblock titulo %}

{% block extrahead %}
<link href="{% static 'style.css' %}" type="text/css" rel="stylesheet">
{% endblock%}

{% block content %}

    <div class="row justify-content-center">
        <div class="col-md-6 col-xs-12">
            <div class="card">
                <header class="card-header">
                    <a href="{% url "person:create" %}" class="float-right btn btn-outline-primary mt-1">Sign up</a>
                    <h4 class="card-title mt-2">Log in</h4>
                </header>
                <article class="card-body">
                    {% if messages %}
                        {% for message in messages %}
                        <p class="text-success">{{message}}</p>
                        {% endfor %}
                    {% endif %}
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <p class="text-danger">{{ error|escape }}</p>
                            {% endfor %} 
                        {% endfor %}
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>User</label>
                            <input class="form-control" type="text" name="username">
                        </div> <!-- form-group end.// -->
                        <div class="form-group">
                            <label>Create password</label>
                            <input class="form-control" type="password" name="password">
                        </div> <!-- form-group end.// -->
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Log in </button>
                        </div> <!-- form-group// -->
                    </form>
                </article> <!-- card-body end .// -->
                <div class="border-top card-body text-center">Don't have an account? <a href="{% url "person:create" %}">Sign up</a></div>
            </div> <!-- card.// -->
        </div> <!-- col.//-->

    </div> <!-- row.//-->



{% endblock%}